### ISSUE TITLE
katex , mathjax が使えない問題

### ISSUE THREAD

**Issue by Seasawher** [lean-ja/math-in-type-theory-ja#1]
ローカルでプレビューする分には mdbook-katex が使えるのですが，GitHub Pages にデプロイする段階でうまくいかなくなります．

mdbook のデフォルトの mathjax サポートだと `$` `$` で囲ってもうまくいきません．

mdbook-katex の GitHub Action を使っているのですが，それが通らないようです．

Action がうまく通るようにするより，markdown ファイルにある数式の部分を全部書き換えたほうが早いかもしれません．

**Comment by Seasawher** [comment]
@aconite-ac 唐突にメンションしてすみません。解決策をご存知ないですか？

**Comment by aconite-ac** [comment]
mdbookのデフォルトのMathJaxサポートを使う場合、
[MathJax Support - mdBook Documentation](https://rust-lang.github.io/mdBook/format/mathjax.html)によると`$ ... $`や`$$ ... $$`の代わりに`\\( ... \\)`を使う必要があるようです。

ローカルで試したところ、デプロイで生成されたhtmlファイルではMathJaxにより正常に数式が表示されましたので、
KaTeXにこだわりがなければ、MathJaxサポートを使った上で、
ソースのmdファイル内の`$ ... $`を`\\( ... \\)`に書き換えるのを試してみてください。

mdbook-katexを使った方法についてはよく分りません…が、
[mdbook-katex 0.1.1 - Docs.rs](https://docs.rs/crate/mdbook-katex/0.1.1)によると、`book.toml`に
```
[preprocessor.katex]
command = "mdbook-katex"
```
と書くことが必要のように見えます。

GitHub Actionの不備だった場合は自分には全く分からないですね…。
GitHub Actionに詳しい方がいるといいのですが…。

**Comment by Seasawher** [comment]
ご確認ありがとうございました。

book.toml の編集試してみます！

それでダメなら、$で囲っている部分を編集してmathjaxが効くようにして、とりあえず対処します

**Comment by Seasawher** [comment]
だめでした．`mdbook-katex` の利用は諦めることにします．（Action のメンテがされていないようなので，そのせいかもしれません）

訳文のチェックをお願いできませんか？

時間があるときに `$` を置換する作業を進めておきます．

**Comment by aconite-ac** [comment]
問題の切り分けのため、こちらのローカル環境にも`mdbook_katex`をインストールし、
このリポジトリのソースをダウンロードしてそのままビルドしてみました。
ビルド結果を確認したところ、数式はKaTeXにより正常に表示されていました。

以上より、問題の原因は、GitHub Actionの設定不備か、環境の問題だと思われます。
Rust本体、`mdbook`、`mdbook_katex`の最新版がインストールされていれば環境としては十分だと思いますが、
GitHub Actionが実行される環境がこの条件を満たしていないのだと考えられます。

`mdbook`のActionを引っ張ってきているように見えるため、
個人的にはGitHub Actionが実行される環境に`mdbook_katex`がインストールされていないのではないか、と疑っています。

**Comment by aconite-ac** [comment]
訳文のチェックはお引き受けいたします。
訳文チェック用のIssueを建ててくだされば、そこでフィードバックいたします。

ただ、進めたい別件があるため、取り掛かるまでに2日ほど掛かるかもしれませんが……、ご了承いただければと思います。

**Comment by Seasawher** [comment]
気合と根性で解決しました．

解決方法ですが，コミット内容をみていただければわかりますが，手動で mathjax のスクリプトをHTMLに入れて，デリミタの設定をするようにしました．

読み込みは遅いですが，一応数式がちゃんと表示されますし，`$` で囲う記法もそのまま使えるようです．

調査してくださってありがとうございました．
