### ISSUE TITLE
文字がなぜか太くなる

### ISSUE THREAD

**Issue by Seasawher** [lean-ja/math-in-type-theory-ja#12]
iOSのsafariで見たときに、なぜか文字が太めに表示されます

おそらく、指定されたフォントが存在しないことにより、想定されていないフォントが使用されているのだと思います

google web font で日本語フォントを導入すれば解決できるのでは？

**Comment by Seasawher** [comment]
文字が太くなってる状態のスクショ

![IMG_2235](https://github.com/lean-ja/math-in-type-theory-ja/assets/47292598/db53b366-72b5-4d4c-b841-820ce65b9eea)

**Comment by Seasawher** [comment]
@aconite-ac そちらの環境でもこの問題は再現するでしょうか？もし再現されるなら、見た目がかなりダサくなってしまうので（原因不明ですが）修正しようと思います。

**Comment by aconite-ac** [comment]
@Seasawher 

こちらの環境(OS: iOS16.6.1, ブラウザ: Safari)では文字が太くなる問題は再現されませんでした。
iOS17固有の問題のようですね…。

**Comment by Seasawher** [comment]
@aconite-ac 確認ありがとうございます．では今後の Apple の修正に期待して，いったん放置しておきます
