### ISSUE TITLE
訳文のレビュー

### ISSUE THREAD

**Issue by Seasawher** [lean-ja/math-in-type-theory-ja#2]
@aconite-ac よろしくお願いします

**Comment by haruhisa-enomoto** [comment]
原文ダッシュをアンダーバーで表しているのは、日本語だとあまり見ず不自然な気がするので、通常用いられるであろう全角ダッシュ2つ「――」や「:」のほうがよいような気がします。

**Comment by aconite-ac** [comment]
ソースのmdファイルの中で、段落内で改行すると、実際の文書上では半角スペースとして表示されます。
この仕様は、単語や文の区切り文字として半角スペースを用いる英語の文書とは相性がよいですが、
日本語の文書だと不必要な半角スペースが随所に挿入されることになり、
見栄えが良くない・記法が統一されていないという印象を与えてしまいます。

以上の理由により、ソースの段落内では極力改行を控えた方がよいと思います。

**Comment by Seasawher** [comment]
ソースが横に長くなるのを防ぐために100字を目安にキリの良いところで折り返すようにしてあるのですが、画面端で折り返す設定にして、段落内の改行をなくそうということでしょうか？

**Comment by Seasawher** [comment]
訳文の正確さについても何かあればコメントお願いします

**Comment by Seasawher** [comment]
> 原文ダッシュをアンダーバーで表しているのは、日本語だとあまり見ず不自然な気がするので、通常用いられるであろう全角ダッシュ2つ「――」や「:」のほうがよいような気がします。

修正しました．

**Comment by aconite-ac** [comment]
> ソースが横に長くなるのを防ぐために100字を目安にキリの良いところで折り返すようにしてあるのですが、画面端で折り返す設定にして、段落内の改行をなくそうということでしょうか？

そうですね、html上の表示を優先して、ソース上の表示はエディタの設定に任せるという提案でした。

ただ、mdBookのレンダリングの際に「段落内の改行を無視する」という設定ができるなら、
それがベストだとは思います。(申し訳ないですが、自分にはその設定方法は分かりません。)

**Comment by aconite-ac** [comment]
訳文のレビューは明日まとまった時間を取ってやる予定です(お待たせしてしまいすみません)

**Comment by aconite-ac** [comment]
@Seasawher 
遅ればせながら、訳文のレビューを始めました。
変更点を分かりやすく示すため、Pull Requestを送らせて頂きました。
お時間のあるときにご確認お願いします。
この方法で良さそうなら、以降の章についても章ごとにPull Requestを送らせて頂きます。

**Comment by Seasawher** [comment]
ありがとうございます

**Comment by Seasawher** [comment]
@aconite-ac 

お疲れさまです．レビューありがとうございました．

レビューが完了したかと思うので，この issue もクローズしようかと思っていますが，訳注をつけてもいいかなと思いました．

途中に出てくる natural number game のリンクは lean3 に対するものです．Lean4 版もあるよという訳注をつけた方がいい気がしました．

訳注については，こちらで検討してPRを出そうかと思いますが，どうでしょうか？

**Comment by aconite-ac** [comment]
@Seasawher

Kitamadoさんも翻訳お疲れ様でした！
natural number gameに関する訳注はあった方がなお良さそうですね。
KitamadoさんからPRを出して頂けるとありがたいです。
レビュー不要でマージもKitamadoさんがやって頂いて良いと思いますが、
他人によるレビュー・マージが必要だと思われた場合は、自分は引き受けいたします。
(PRの時間帯によっては今晩の対応になるかもしれません…。)

**Comment by Seasawher** [comment]
訳注を付けたうえで，段落内の改行も削除しました．
